[2025-09-17T05:45:11.809+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: equities_eod_batch_dag.batch_equities_eod manual__2025-09-17T05:44:47.999226+00:00 [queued]>
[2025-09-17T05:45:11.952+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: equities_eod_batch_dag.batch_equities_eod manual__2025-09-17T05:44:47.999226+00:00 [queued]>
[2025-09-17T05:45:11.959+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-17T05:45:12.288+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): batch_equities_eod> on 2025-09-17 05:44:47.999226+00:00
[2025-09-17T05:45:12.997+0000] {standard_task_runner.py:60} INFO - Started process 935 to run task
[2025-09-17T05:45:13.215+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'equities_eod_batch_dag', 'batch_equities_eod', 'manual__2025-09-17T05:44:47.999226+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/equities_eod_batch_dag.py', '--cfg-path', '/tmp/tmp2cjay4eo']
[2025-09-17T05:45:13.378+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask batch_equities_eod
[2025-09-17T05:45:15.189+0000] {task_command.py:423} INFO - Running <TaskInstance: equities_eod_batch_dag.batch_equities_eod manual__2025-09-17T05:44:47.999226+00:00 [running]> on host 5940dd694332
[2025-09-17T05:45:20.936+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ho' AIRFLOW_CTX_DAG_ID='equities_eod_batch_dag' AIRFLOW_CTX_TASK_ID='batch_equities_eod' AIRFLOW_CTX_EXECUTION_DATE='2025-09-17T05:44:47.999226+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-17T05:44:47.999226+00:00'
[2025-09-17T05:45:21.913+0000] {logging_mixin.py:188} WARNING - /opt/***/scripts/equities_eod_writer.py:11 FutureWarning: YF.download() has changed argument auto_adjust default to True
[2025-09-17T05:45:26.753+0000] {logging_mixin.py:188} WARNING - [                       0%                       ]
[2025-09-17T05:45:26.752+0000] {logging_mixin.py:188} WARNING - [                       0%                       ]
[2025-09-17T05:45:26.793+0000] {logging_mixin.py:188} WARNING - [*********************100%***********************]  3 of 3 completed
[2025-09-17T05:45:28.883+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/equities_eod_writer.py", line 22, in run_equities_eod_writer
    client.fput_object(BUCKET, s3_path, file_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 1053, in fput_object
    return self.put_object(
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 2008, in put_object
    raise exc
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 1954, in put_object
    return self._put_object(
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 1783, in _put_object
    response = self._execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 440, in _execute
    region = self._get_region(bucket_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 497, in _get_region
    response = self._url_open(
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 426, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: NoSuchBucket, message: The specified bucket does not exist, resource: /quant, request_id: 1865FBA806A0A9AB, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: quant
[2025-09-17T05:45:29.024+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=equities_eod_batch_dag, task_id=batch_equities_eod, execution_date=20250917T054447, start_date=20250917T054511, end_date=20250917T054528
[2025-09-17T05:45:29.342+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task batch_equities_eod (S3 operation failed; code: NoSuchBucket, message: The specified bucket does not exist, resource: /quant, request_id: 1865FBA806A0A9AB, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: quant; 935)
[2025-09-17T05:45:29.510+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-17T05:45:30.037+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
